# Cuppen's Divide-and-Conquer Algorithm

In [3]:
import numpy as np
from numpy.random import randint

%matplotlib inline

## Divide-and-Conquer Algorithms

Divide-and-conquer algorithms are a general class of methods that utilize recursion to break down a problem into subproblems, which can be solved more easily. They consist of three stages:
1. Divide:
2. Conquer:
3. Combine:

One such example is a merge sort.

<img src="img/binarysort.png" alt="term-document matrix" style="width: 40%"/>

Given a list of eight numbers to sort, the problem can be split into two lists of four numbers. These two lists can then be split again into four lists of two numbers (divide). Sorting two numbers, then, is a trivial task (conquer). Once sorted, these numbers can be put back together in order until the original list is returned sorted (combine).

Link: https://medium.com/brandons-computer-science-notes/divide-and-conquer-algorithms-4e83d9999ffa

## Cuppen's Divide-and-Conquer Algorithm

J.J.M. Cuppen suggested a method to calculate the eigenvalues of a symmetric tridiagonal matrix, which he showed was an order of magnitude faster than the QR method.

Link: https://www2.eecs.berkeley.edu/Pubs/TechRpts/1994/CSD-94-799.pdf

<img src="img/divideconquertree.png" alt="term-document matrix" style="width: 70%"/>

The basic principle is to divide the original problem (level 0) into subproblem recursively to the point that solving the subproblems is trivial (level 3). Once at the lowest level, the algorithm can return back up the tree to provide solutions to the preceding subproblems.

### Helper methods

In [49]:
def divide(T):
    m = T.shape[0]
    n = int(np.ceil(m / 2))
        
    T1 = np.array(T[:n, :n], dtype=float)
    T2 = np.array(T[n:, n:], dtype=float)
    
    a = np.abs(T[n, n-1])
    T1[-1, -1] -= a
    T2[0, 0] -= a
    
    b = np.zeros((m,1))
    b[[n-1,n]] += 1
    
    return T1, T2, b, a


def cuppen(T):
    if T.shape[0] > 3:
        T1, T2, b, a = cuppen(T1)
        T1, T2, b, a = cuppen(T2)
        print(T1, T2)
    else:
        q, r = np.linalg.qr(T)
    
    

### Example

Create a random tridiagonal matrix of integers.

In [50]:
n = 5
x = 10

off_diag = randint(1, x, size=n-1)
T = np.diag(off_diag, k=1) + np.diag(randint(1, x, size=n)) + np.diag(off_diag, k=-1)

print(T)

[[5 7 0 0 0]
 [7 7 3 0 0]
 [0 3 9 5 0]
 [0 0 5 8 4]
 [0 0 0 4 3]]


Divide the tridiagonal matrix

In [52]:
T1, T2, b, a = cuppen(T)
print(T1, T2, b, a)

[[5. 7. 0.]
 [7. 7. 3.]
 [0. 3. 4.]] [[3. 4.]
 [4. 3.]]


TypeError: 'NoneType' object is not iterable

Compare the original and decomposed matrix

In [45]:
r1, c1 = T1.shape
r2, c2 = T2.shape

T_recon = np.block([[T1, np.zeros((r1, c2))], [np.zeros((r2, c1)), T2]]) + a * b @ b.T

np.allclose(T, T_recon)

True