# Preconditioner Series: Introduction to Preconditioners

When solving linear systems such as $Ax=b$ iteratively, the condition number, $\kappa$, of $A$ is indicative of the rate of convergence. Preconditioners ($P$), then, "massage" these linear systems to have lower conditioner numbers, and, thus, higher rates of convergence.

$$ \kappa(P^{-1}A)\ \text{,}\  \kappa(AP^{-1}) << \kappa(A) $$

The linear system can be right or left preconditioned:

Right preconditioned system
1. Introduce $P^{-1}P=I$
$$ AP^{-1}Px=b $$
2. Solve for $y$
$$ AP^{-1}y=b $$
3. Solve for $x$
$$ Px=y $$

Left preconditioned system
1. Multiply both sides by $P^{-1}$
$$ P^{-1}Ax=P^{-1}b $$
2. Gather terms on left side
$$ P^{-1}(Ax-b)=0 $$

## Imports

In [19]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

Here, I demonstrate the effectiveness of preconditioning by solving a linear system before and after preconditioning. Though a variety of iterative methods exist, I will employ one of the simplest - the Jacobi method.

It's so simple, in fact, that a function hardly seems necessary, but I will make one to make it clear what preconditioner is being used when solving linear systems later.

The matrix A is decomposed into the diagonal, $D$, and the off-diagonal, $R$.

$$ A=D+R $$

Then, given $x^{(k)}$, $x^{(k+1)}$ is calculated as:

$$ x^{(k+1)}=D^{-1}(b-Rx^{(k)}) $$

Typically, calculating the inverse of a matrix is unfavorable; however, because $D$ is a diagonal matrix, its inverse is trivially easy to calculate: it is simply the reciprocal of the diagonal elements.

In [34]:
def jacobi_method(A, x0, b, rtol=1e-5, atol=1e-8, max_iter=1000):
    
    # find inverse of diagonal matrix and off-diagonal matrix
    D_inv, R = np.diag(np.reciprocal(np.diagonal(A))), A - np.diag(np.diagonal(A))
    
    i = 0
    x = x0
    
    # loop for max_iter iterations or until converged
    while(i < max_iter):
        x_new = D_inv @ (b - R @ x)
        if (i % 100 == 0):
            print('Iteration:' + str(i))
        
        # test convergence
        if (np.allclose(x, x_new, rtol, atol)):
            print('Iterations to convergence: ' + str(i))
            return x_new
        
        # prep for next iteration
        x = x_new
        i += 1
        
    # solution did not converge
    print('Maximum number of iterations reached. Did not converge.')

First we create a random matrix $A$.

In [43]:
n = 3
# A = np.random.rand(n, n)
A = np.matrix([[2, 1], [5, 7]]); A

matrix([[2, 1],
        [5, 7]])

Now, we create a random vector $b$.

In [53]:
# b = np.random.rand(n,); b
b = np.array([[11],[13]]); b

array([[11],
       [13]])

Now that we iteratively solve for $x$.

The first step is to provide an initial estimate for $x$, which I'll call $x^{(0)}$.

In [51]:
x0 = np.ones((len(b), 1)); x0

array([[1.],
       [1.]])

Now, we can pass $A$, $x^{(0)}$, and $b$ and begin iteratively solving for $x$.

In [55]:
x = jacobi_method(A, x0, b, rtol=1e-4, atol=1e-4, max_iter=1000); x

Iteration:0
Iterations to convergence: 1


matrix([[0.],
        [0.]])

## Resources

[Iterative Methods for Sparse Linear System](https://www.amazon.com/Iterative-Methods-Sparse-Linear-Systems/dp/0898715342)