# QR Factorization

Having been referred to as "the most important algorithm in linear algebra" by [Trefethen and Bau](https://www.amazon.com/Numerical-Linear-Algebra-Lloyd-Trefethen/dp/0898713617), it was only fair that QR factorization received its own notebook.

Here, I go into the details of its implementation and its applications for other algorithms in numerical linear algebra.

## Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Helper methods

## First, the proof...

The result of the QR factorization is fairly simple, however, its proof was not as simple to grasp. The following excerpt was adapted from [Golub and Van Loan's work](https://www.amazon.com/Computations-Hopkins-Studies-Mathematical-Sciences/dp/1421407949).

**Theorem.** For a rectangular matrix $A\in \mathbb R^{m\times n}$, there exists an orthogonal matrix $Q\in \mathbb R^{m\times m}$ and an upper triangular $R\in \mathbb R^{m\times n}$ such that $A=QR$.

**Proof.** Suppose $n=1$ and that $Q$ is a Householder matrix so that if $R=Q^TA$, then $R(2:m)=0$. It follows that $A=QR$ is a $QR$ factorization of $A$. For general $n$, we partition $A$ as $A=[A_1|v]$ where $v=A(:,n)$. 

Therefore, there exists an orthogonal $Q_1\in \mathbb R^{m\times m}$ so that $R_1=Q_1^TA_1$ is upper triangular. 

Set $w=Q^Tv$ and let $w(n:m)=Q_2R_2$ be the $QR$ factorization of $w(n:m)$. If

$$ Q=Q_1\begin{bmatrix}I_{n-1} & 0 \\ 0 & Q_2 \end{bmatrix} \text{,}$$

then

$$ A=Q\begin{bmatrix}R_1|w(1:n-1) \\ R_2 \end{bmatrix}$$

is a $QR$ factorization of $A$.

### Step-by-step visualization of proof

**Suppose $n=1$ and that $Q$ is a Householder matrix so that if $R=Q^TA$, then $R(2:m)=0$.**

A Householder matrix is constructed by the linear transformation that describes a reflection about a plane containing the origin. The plane is defined by a unit vector $v$ that is orthogonal to the plane. The reflection of a point $x$ about this plane is expressed as:

$$ x-2v(v^Hx) $$

In matrix form, this is:

$$ P=I-2vv^H $$

where $v^H$ is the conjugate transpose of $v$, but if $v$ is real $v^H=v^T$.

Let's say that $m=3$. 

In [24]:
A = np.array([[6, 6, 1],
              [3, 6, 1],
              [2, 1, 1]])

In [23]:
R = Q.T @ A; R

array([-29., -38., -35., -32., -37.])

**It follows that $A=QR$ is a $QR$ factorization of $A$.**

**For general $n$, we partition $A$ as $A=[A_1|v]$ where $v=A(:,n)$.**

**Therefore, there exists an orthogonal $Q_1\in \mathbb R^{m\times m}$ so that $R_1=Q_1^TA_1$ is upper triangular.**

**Set $w=Q^Tv$ and let $w(n:m)=Q_2R_2$ be the $QR$ factorization of $w(n:m)$.**

**If**

$$ Q=Q_1\begin{bmatrix}I_{n-1} & 0 \\ 0 & Q_2 \end{bmatrix} \text{,}$$

**then**

$$ A=Q\begin{bmatrix}R_1|w(1:n-1) \\ R_2 \end{bmatrix}$$

**is a $QR$ factorization of $A$.**

## And now, the algorithms

Like every factorization in numerical linear algebra, there are multiple algorithms to calculate the QR factorization of a given matrix:
- Householder QR
- Block Householder QR
- Block recursive QR
- Givens QR methods
- Hessenberg QR via Givens
- Classical Gram-Schmidt
- Modified Gram-Schmidt

## Householder QR

For $A\in \mathbb R^{m\times n}$ where $m\geq n$, the following algorithm finds Householder matrices $H_1,\dots,H_n$ such that $Q^TA=R$ is upper triangular where $Q=H_1H_2\cdot\cdot\cdot H_n$.

<img src="img/house_qr.png" alt="term-document matrix" style="width: 50%"/>

For additional explanations, I would recommend [Professor Driscoll's video on Householder QR](https://www.youtube.com/watch?v=d-yPM-bxREs).

In [13]:
def house(x):
    m = len(x)
    sig = np.linalg.norm(x[1:]) ** 2
    v = np.append([1.], x[1:])
    
    if sig == 0 and x[0] >= 0:
        beta = 0
    elif sig == 0 and x[0] < 0:
        beta = -2
    else:
        mu = np.sqrt(x[0] ** 2 + sig)
        if x[0] <= 0:
            v[0] = x[0] - mu
        else:
            v[0] = -sig / (x[0] + mu)
            
        v /= v[0]
        beta = 2 * v[0] ** 2 / (sig + v[0] ** 2)
    
    return v, beta
    
def house_qr(A):
    m, n = A.shape
    
    for j in range(n):
        v, beta = house(A[j:m, j])        
        A[j:m, j:n] = (np.eye(m - j) - beta * v @ v.T) @ A[j:m, j:n]
        if j < m:
            A[j + 1:m, j] = v[1:m - j + 1]
            
    return Q, R

A = np.array([[2, -2, 18],
              [2, 1, 0],
              [1, 2, 0]])

Q, R = house_qr(A)
np.allclose(A, Q @ R)

KeyboardInterrupt: 

In [48]:
A = np.array([[6, 6, 1],
              [3, 6, 1],
              [2, 1, 1]])

Q, R = house_qr(A)
np.allclose(A, Q @ R)

[[-1. -2. -2.]
 [-2. -1. -2.]
 [-2. -2. -1.]]
[[ 0.99606709 -0.00393291 -0.00393291]
 [-0.00393291  0.99606709 -0.00393291]
 [-0.00393291 -0.00393291  0.99606709]]


ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## Block Householder QR

## Block recursive QR

## Givens QR methods

In [ ]:
def givens_qr(A):
    

## Hessenberg QR via Givens

## QR with Wilkinson shifts

## Classical Gram-Schmidt

## Modified Gram-Schmidt

## Resources

[fast.ai Computational Linear Algebra course](https://www.fast.ai/2017/07/17/num-lin-alg/)

[Numerical Linear Algebra by Lloyd N. Trefethen and David Bau III](https://www.amazon.com/Numerical-Linear-Algebra-Lloyd-Trefethen/dp/0898713617)

[Matrix Computations by Gene H. Golub and Charles F. Van Loan (4th Ed.)](https://www.amazon.com/Computations-Hopkins-Studies-Mathematical-Sciences/dp/1421407949)